name: Jaclyn G Photography
favicon: null
layout_spectrum: 0.2798
typography_spectrum: 0.50606
title: 'jaclyn g '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7ddf4'
    - '#1a1718'
    - '#6c6c6c'
    - '#ff8b7e'
    - '#d06a68'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
